name: Deploy Backend to Heroku

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Configure git user
        run: |
          git config --global user.email ${{ secrets.HEROKU_USER_EMAIL }}
          git config --global user.name ${{ secrets.HEROKU_USER_NAME }}

      - name: Set up Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          echo "Heroku CLI installed successfully"

      - name: Set up Heroku authentication
        run: |
          echo "machine git.heroku.com login ${{ secrets.HEROKU_USER_NAME }} password ${{ secrets.HEROKU_API_KEY }}" > ~/.netrc
      
      # Bước 2: Gán biến môi trường FRONTEND_URL vào Heroku Config Vars
      # Sử dụng secrets đã lưu trên GitHub
      - name: Set Heroku Config Var (FRONTEND_URL)
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_BACKEND_APP_NAME }}
          FRONTEND_URL_VALUE: ${{ secrets.FRONTEND_URL }}
          FIREBASE_KEY_CONTENT: ${{ secrets.FIREBASE_KEY_CONTENT }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_ADMIN_CHAT_ID: ${{ secrets.TELEGRAM_ADMIN_CHAT_ID }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        run: |
          heroku config:set FRONTEND_URL=$FRONTEND_URL_VALUE --app $HEROKU_APP_NAME
          heroku config:set FIREBASE_SERVICE_ACCOUNT_KEY_JSON="$FIREBASE_KEY_CONTENT" -a $HEROKU_APP_NAME
          heroku config:set TELEGRAM_BOT_TOKEN="$TELEGRAM_BOT_TOKEN" -a $HEROKU_APP_NAME
          heroku config:set TELEGRAM_ADMIN_CHAT_ID="$TELEGRAM_ADMIN_CHAT_ID" -a $HEROKU_APP_NAME
          heroku config:set CLOUDINARY_CLOUD_NAME="$CLOUDINARY_CLOUD_NAME" -a $HEROKU_APP_NAME
          heroku config:set CLOUDINARY_API_KEY="$CLOUDINARY_API_KEY" -a $HEROKU_APP_NAME
          heroku config:set CLOUDINARY_API_SECRET="$CLOUDINARY_API_SECRET" -a $HEROKU_APP_NAME
      
      - name: Set the buildpack for backend
        run: |
          cd backend
          heroku buildpacks:set heroku/nodejs --app ${{ secrets.HEROKU_BACKEND_APP_NAME }}
      - name: Fetch all commits (Unshallow)
        run: |
          git fetch --all --unshallow

      # - name: Deploy to Heroku
      #   run: |
      #     cd backend
      #     git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git
      #     git add .
      #     git commit -m "Deploy backend to Heroku"
      #     git push heroku main
      - name: Deploy backend subtree to Heroku root
        run: |
          # Thêm remote Heroku (chạy từ gốc repo)
          # Kiểm tra xem remote đã tồn tại chưa để tránh lỗi
          git remote remove heroku || true
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git

          # Push nội dung của thư mục 'backend' lên làm gốc của nhánh 'main' trên remote 'heroku'
          # Lệnh này sẽ tạo một commit mới chỉ chứa nội dung của 'backend' và đẩy lên
          # Dùng --force để ghi đè nhánh trên Heroku
          echo "Pushing backend subtree to Heroku app root..."
          git subtree push --prefix backend heroku main
        env:
          # Vẫn cần các biến môi trường cho git push qua HTTPS
          GIT_ASKPASS: echo
          GIT_USERNAME: ${{ secrets.HEROKU_USER_EMAIL }} # Hoặc placeholder
          GIT_PASSWORD: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} # Có thể cần cho các lệnh khác nếu có

