name: Deploy Frontend to Heroku

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Check if package.json exists in frontend
        run: |
          cd frontend
          ls -la
          if [ -f "package.json" ]; then
            echo "package.json found"
          else
            echo "package.json not found"
            exit 1
          fi

      - name: Configure git user
        run: |
          git config --global user.email ${{ secrets.HEROKU_USER_EMAIL }}
          git config --global user.name ${{ secrets.HEROKU_USER_NAME }}
    
      - name: Set up Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          echo "Heroku CLI installed successfully"

      - name: Set up Heroku authentication
        run: |
          echo "machine git.heroku.com login ${{ secrets.HEROKU_USER_NAME }} password ${{ secrets.HEROKU_API_KEY }}" > ~/.netrc

      # Bước 2: Gán biến môi trường NPM_CONFIG_PRODUCTION vào Heroku Config Vars
      # Sử dụng secrets đã lưu trên GitHub
      - name: Set Heroku Config Var (NPM_CONFIG_PRODUCTION)
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          NPM_CONFIG_PRODUCTION: ${{ secrets.NPM_CONFIG_PRODUCTION }}
        run: heroku config:set NPM_CONFIG_PRODUCTION=$NPM_CONFIG_PRODUCTION --app ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
    
      - name: Set the buildpack for frontend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # <-- Sử dụng secret đã lưu
          HEROKU_APP_NAME: ${{ secrets.HEROKU_FRONTEND_APP_NAME }} # Giả sử tên app cũng là secret
        run: |
          cd frontend
          # heroku buildpacks:clear --app ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
          # heroku buildpacks:add --index 1 'heroku/nodejs' --app ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
          # heroku buildpacks:add --index 2 'heroku/nginx' --app ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
          # echo "Buildpacks set (hopefully!)"
          # heroku buildpacks --app ${{ secrets.HEROKU_FRONTEND_APP_NAME }} # Thêm lệnh này để kiểm tra ngay trong log CI/CD
    
      - name: Fetch all commits (Unshallow)
        run: |
          git fetch --all --unshallow

      - name: Check for changes
        run: |
          cd frontend
          git status
    
      - name: Build Frontend Application
        # Truyền secret vào làm biến môi trường cho quá trình build của Vite
        env:
          VITE_SOCKET_URL: ${{ secrets.VITE_SOCKET_URL }}
        run: npm run build --prefix frontend # Chạy script build
    #   - name: Deploy to Heroku
    #     run: |
    #       cd frontend
    #       ls -la
    #       git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_FRONTEND_APP_NAME }}.git
    #       git add .
    #       git commit -m "Deploy to Heroku" || echo "No changes to commit"
    #       git push heroku main
    #     env:
    #       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    # --- Bước Deploy chính: Dùng git subtree push ---
      - name: Deploy frontend subtree to Heroku root
        run: |
          # Thêm remote Heroku (chạy từ gốc repo)
          # Kiểm tra xem remote đã tồn tại chưa để tránh lỗi
          git remote remove heroku || true
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_FRONTEND_APP_NAME }}.git

          # Push nội dung của thư mục 'frontend' lên làm gốc của nhánh 'main' trên remote 'heroku'
          # Lệnh này sẽ tạo một commit mới chỉ chứa nội dung của 'frontend' và đẩy lên
          # Dùng --force để ghi đè nhánh trên Heroku
          echo "Pushing frontend subtree to Heroku app root..."
          git subtree push --prefix frontend heroku main
        env:
          # Vẫn cần các biến môi trường cho git push qua HTTPS
          GIT_ASKPASS: echo
          GIT_USERNAME: ${{ secrets.HEROKU_USER_EMAIL }} # Hoặc placeholder
          GIT_PASSWORD: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} # Có thể cần cho các lệnh khác nếu có
